CREATE TABLE IF NOT EXISTS `golinks`.`LinksTable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `userid` BIGINT NULL,
  `name` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  `hits` BIGINT DEFAULT 0,
  `created_at` DATETIME DEFAULT  CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
